#!/usr/bin/env bash

# set variable for argument 1
commit_description="$1"

# add files to git submission
git -C ~/gits/dotfiles-desktop/ add .

# describe git submission and commit
git -C ~/gits/dotfiles-desktop/ commit "-m $commit_description"

# push changes to git
git -C ~/gits/dotfiles-desktop/ push origin main
